spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

s3:
  endpoint: ${S3_URL}
  bucket: ${S3_BUCKET}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  presign-exp-seconds: 300

