spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 100

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
