spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 100

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      minimum-idle: 0
      idle-timeout: 240000
